name: Deploy Static Website to GitHub Pages

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - master  # Or use 'master' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
        publish_dir: ./  # Publish the root directory (since you have only HTML/CSS files in the root)
        publish_branch: deployed-branch  # Branch to deploy to (typically 'gh-pages')
